export default {
  at: '2022-04-11T20:15:27.940Z',
  products: [
    {
      description: 'id nulla officia eu',
      name: 'ex',
      price: 1732.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'id qui irure incididunt',
      name: 'Lorem',
      price: 208.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliquip culpa pariatur ad',
      name: 'eu',
      price: 976.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ut pariatur nisi nulla',
      name: 'anim',
      price: 957.52,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nostrud qui aute Lorem',
      name: 'nulla',
      price: 1825.52,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'est nisi duis labore',
      name: 'aliquip',
      price: 501.16,
      tmpProperty: undefined,
      activePromoId: 49,
    },
    {
      description: 'labore incididunt tempor incididunt',
      name: 'dolor',
      price: 1267.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'non laborum quis consequat',
      name: 'excepteur',
      price: 1657.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum veniam ad magna',
      name: 'amet',
      price: 777.95,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: 'officia laborum anim amet',
      name: 'adipisicing',
      price: 1335.96,
      tmpProperty: undefined,
      activePromoId: 97,
    },
    {
      description: 'deserunt consectetur proident esse',
      name: 'aliquip',
      price: 318.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'minim adipisicing ad qui',
      name: 'non',
      price: 505.18,
      tmpProperty: undefined,
      activePromoId: 29,
    },
    {
      description: 'in aute fugiat velit',
      name: 'aliquip',
      price: 1767.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'occaecat est incididunt nisi',
      name: 'duis',
      price: 173.57,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'Lorem sint magna excepteur',
      name: 'non',
      price: 275.89,
      tmpProperty: undefined,
      activePromoId: 2,
    },
    {
      description: 'ex tempor voluptate commodo',
      name: 'laborum',
      price: 506.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'officia proident pariatur consectetur',
      name: 'Lorem',
      price: 222.62,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: 'dolor velit incididunt cupidatat',
      name: 'ex',
      price: 911.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'duis quis dolor laboris',
      name: 'pariatur',
      price: 1374.19,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: 'officia sint voluptate id',
      name: 'sit',
      price: 1552.43,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: 'exercitation sunt deserunt est',
      name: 'mollit',
      price: 662.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'qui nostrud Lorem aliquip',
      name: 'nulla',
      price: 336.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo nisi et dolore',
      name: 'id',
      price: 1190.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'duis cupidatat commodo quis',
      name: 'pariatur',
      price: 1609.56,
      tmpProperty: undefined,
      activePromoId: 60,
    },
    {
      description: 'nostrud commodo eu ex',
      name: 'sit',
      price: 926.13,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'occaecat exercitation adipisicing occaecat',
      name: 'nostrud',
      price: 189.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cillum non eiusmod voluptate',
      name: 'aute',
      price: 1114.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse quis sit reprehenderit',
      name: 'ipsum',
      price: 1164.72,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: 'reprehenderit nisi quis officia',
      name: 'veniam',
      price: 177.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse id ex ut',
      name: 'elit',
      price: 337.09,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: 'magna ullamco tempor exercitation',
      name: 'in',
      price: 1645.53,
      tmpProperty: undefined,
      activePromoId: 37,
    },
    {
      description: 'reprehenderit non aliquip aute',
      name: 'adipisicing',
      price: 219.32,
      tmpProperty: undefined,
      activePromoId: 28,
    },
    {
      description: 'cupidatat ea cupidatat et',
      name: 'veniam',
      price: 1998.25,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: 'esse nisi dolore anim',
      name: 'aliqua',
      price: 541.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim Lorem incididunt magna',
      name: 'duis',
      price: 1201.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'pariatur voluptate eiusmod exercitation',
      name: 'id',
      price: 452.76,
      tmpProperty: undefined,
      activePromoId: 58,
    },
    {
      description: 'sunt occaecat laboris nulla',
      name: 'esse',
      price: 1242.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ullamco nostrud excepteur amet',
      name: 'aliquip',
      price: 1497.3,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo enim pariatur aute',
      name: 'aute',
      price: 160.1,
      tmpProperty: undefined,
      activePromoId: 62,
    },
    {
      description: 'nulla incididunt deserunt officia',
      name: 'proident',
      price: 1058.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sunt qui magna do',
      name: 'nulla',
      price: 1577.09,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: 'ipsum sit nulla duis',
      name: 'voluptate',
      price: 1057.91,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'mollit magna nulla esse',
      name: 'reprehenderit',
      price: 718.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo officia veniam aliquip',
      name: 'laboris',
      price: 1678.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim ullamco nisi occaecat',
      name: 'nulla',
      price: 1563.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consectetur minim fugiat voluptate',
      name: 'laboris',
      price: 1491.65,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit veniam minim irure',
      name: 'quis',
      price: 1846.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ipsum velit est et',
      name: 'sint',
      price: 386.46,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: 'esse aliqua occaecat do',
      name: 'reprehenderit',
      price: 1247.65,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ea anim sit sunt',
      name: 'minim',
      price: 1399.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ipsum aliquip cupidatat Lorem',
      name: 'irure',
      price: 110.24,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: 'culpa officia mollit amet',
      name: 'occaecat',
      price: 1915.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliqua labore nostrud duis',
      name: 'et',
      price: 999.71,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: 'minim consequat magna nulla',
      name: 'eiusmod',
      price: 891.62,
      tmpProperty: undefined,
      activePromoId: 95,
    },
    {
      description: 'consequat minim ut ex',
      name: 'esse',
      price: 1184.3,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: 'occaecat cupidatat velit ullamco',
      name: 'fugiat',
      price: 1360.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sint dolor minim anim',
      name: 'proident',
      price: 969.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consequat cupidatat mollit anim',
      name: 'dolore',
      price: 318.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'voluptate consequat enim aliqua',
      name: 'amet',
      price: 223.48,
      tmpProperty: undefined,
      activePromoId: 9,
    },
    {
      description: 'eiusmod consectetur nisi voluptate',
      name: 'eiusmod',
      price: 1167.02,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: 'ad dolor reprehenderit id',
      name: 'est',
      price: 1730.67,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: 'fugiat esse deserunt commodo',
      name: 'culpa',
      price: 704.7,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'duis sunt aliqua occaecat',
      name: 'exercitation',
      price: 795.55,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: 'culpa veniam officia ipsum',
      name: 'excepteur',
      price: 1366.37,
      tmpProperty: undefined,
      activePromoId: 73,
    },
    {
      description: 'voluptate eiusmod voluptate elit',
      name: 'in',
      price: 221.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'exercitation excepteur ut eu',
      name: 'dolore',
      price: 1973.87,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'culpa nulla do labore',
      name: 'sint',
      price: 966.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nostrud velit dolor sunt',
      name: 'dolor',
      price: 1000.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'non cupidatat id sunt',
      name: 'magna',
      price: 746.05,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: 'anim qui duis ea',
      name: 'minim',
      price: 1196.63,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: 'exercitation amet labore est',
      name: 'excepteur',
      price: 1545.07,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: 'culpa proident ullamco cupidatat',
      name: 'labore',
      price: 200.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ad laboris in dolor',
      name: 'id',
      price: 1103.64,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {
      description: 'dolor ea ipsum aliqua',
      name: 'fugiat',
      price: 1846.31,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'excepteur dolor ut laborum',
      name: 'minim',
      price: 1010.53,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'non nostrud voluptate mollit',
      name: 'aliqua',
      price: 1008.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'tempor magna aute adipisicing',
      name: 'culpa',
      price: 1765.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse ex occaecat consequat',
      name: 'magna',
      price: 1315.95,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: 'culpa amet velit in',
      name: 'laborum',
      price: 429.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'in esse est mollit',
      name: 'laborum',
      price: 442,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'duis nostrud qui sint',
      name: 'velit',
      price: 796.72,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: 'amet proident fugiat ipsum',
      name: 'eu',
      price: 1239.37,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim voluptate nulla enim',
      name: 'elit',
      price: 1585.38,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: 'nostrud fugiat aliqua dolor',
      name: 'ipsum',
      price: 1022.05,
      tmpProperty: undefined,
      activePromoId: 21,
    },
    {
      description: 'ipsum consequat culpa velit',
      name: 'cupidatat',
      price: 1444.36,
      tmpProperty: undefined,
      activePromoId: 82,
    },
    {
      description: 'qui nulla laborum ea',
      name: 'elit',
      price: 1363.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ea irure quis sunt',
      name: 'esse',
      price: 1871.93,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: 'duis mollit pariatur quis',
      name: 'eu',
      price: 436.9,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: 'pariatur anim nisi minim',
      name: 'sint',
      price: 553.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim officia ut ut',
      name: 'veniam',
      price: 1771.69,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: 'culpa duis ipsum aliquip',
      name: 'commodo',
      price: 993.31,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: 'labore labore nisi ex',
      name: 'non',
      price: 1783.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'adipisicing laboris pariatur adipisicing',
      name: 'voluptate',
      price: 110.04,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum aliqua excepteur excepteur',
      name: 'quis',
      price: 160.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'amet laborum irure consequat',
      name: 'sint',
      price: 1514.02,
      tmpProperty: undefined,
      activePromoId: 33,
    },
    {
      description: 'aliqua pariatur laboris ad',
      name: 'aute',
      price: 800.6,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consectetur eu exercitation minim',
      name: 'cupidatat',
      price: 940.29,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {
      description: 'pariatur aute sint consectetur',
      name: 'occaecat',
      price: 647.45,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'nostrud tempor duis minim',
      name: 'ullamco',
      price: 804.3,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo labore minim non',
      name: 'cupidatat',
      price: 1609.99,
      tmpProperty: undefined,
      activePromoId: 85,
    },
  ],
};
